# Generated by Django 4.2.9 on 2024-04-13 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_software', models.CharField(default=False, max_length=200)),
                ('website', models.CharField(default=False, max_length=50)),
                ('description', models.CharField(default=False, max_length=500)),
                ('software_name', models.CharField(default=False, max_length=50)),
                ('business_areas', models.CharField(default=False, max_length=200)),
                ('modules', models.CharField(default=False, max_length=50)),
                ('financial_services_client_types', models.CharField(default=False, max_length=100)),
                ('created_by', models.CharField(default=False, max_length=200, null=True)),
                ('cloud_type', models.CharField(blank=True, choices=[('cloud_native', 'cloud_native'), ('cloud_based', 'cloud_based'), ('cloud_enabled', 'cloud_enabled')], max_length=200, null=True)),
                ('additional_info', models.CharField(default=False, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default=False, max_length=100)),
                ('address', models.CharField(default=False, max_length=100)),
                ('location_countries', models.CharField(max_length=500)),
                ('company_established', models.PositiveIntegerField(default=False)),
                ('location_cities', models.CharField(max_length=100)),
                ('contact_telephone_no', models.CharField(default=False, max_length=200)),
                ('no_of_employees', models.PositiveIntegerField(default=False)),
                ('internal_professional_services', models.CharField(default=False, max_length=3)),
                ('last_demo_date', models.CharField(default=False, max_length=20)),
                ('last_reviewed_date', models.CharField(default=False, max_length=20)),
                ('document_to_attach', models.FileField(blank=True, default=None, max_length=3, null=True, upload_to='')),
                ('is_client', models.BooleanField(default=False)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=False, max_length=200)),
                ('address', models.CharField(default=False, max_length=100)),
                ('country', models.CharField(max_length=500)),
                ('nationality', models.CharField(max_length=500)),
                ('is_client', models.BooleanField(default=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
