# Generated by Django 4.2.9 on 2024-04-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='website',
        ),
    ]
