# Generated by Django 4.2.9 on 2024-04-02 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_remove_product_company_established_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=False, max_length=100)),
                ('location_countries', models.CharField(max_length=500)),
                ('company_established', models.PositiveIntegerField(default=False)),
                ('location_cities', models.CharField(max_length=100)),
                ('contact_telephone_no', models.CharField(default=False, max_length=200)),
                ('no_of_employees', models.PositiveIntegerField(default=False)),
                ('internal_professional_services', models.CharField(default=False, max_length=3)),
                ('last_demo_date', models.CharField(default=False, max_length=20)),
                ('last_reviewed_date', models.CharField(default=False, max_length=20)),
                ('document_to_attach', models.FileField(default=False, max_length=3, upload_to='')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=False, max_length=200)),
                ('address', models.CharField(default=False, max_length=100)),
                ('country', models.CharField(max_length=500)),
                ('nationality', models.CharField(max_length=500)),
                ('email', models.EmailField(default=False, max_length=254, unique=True, verbose_name='email address')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
