# Generated by Django 4.2.9 on 2024-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_product_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.CharField(default="Street name and zipcode", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="company_established",
            field=models.PositiveIntegerField(default="Year of establishment"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="company_name",
            field=models.CharField(default="Name of Organization", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact_telephone_no",
            field=models.CharField(default="+44-123-4567", max_length=200),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="last_demo_date",
            field=models.CharField(default="dd-mm-yyyy", max_length=20),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="last_reviewed_date",
            field=models.CharField(default="dd-mm-yyyy", max_length=20),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="no_of_employees",
            field=models.PositiveIntegerField(default="1-100000"),
        ),
    ]
