# Generated by Django 4.2.9 on 2024-04-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vendor_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
