# Generated by Django 4.2.9 on 2024-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_is_student_client_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
