# Generated by Django 4.2.9 on 2024-04-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_vendor_document_to_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
