# Generated by Django 4.2.9 on 2024-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
